SYSFILE_BASIC_URL = "basic"
CPU_LOAD_URL = "load"
CPU_BASEINFO_URL = "baseinfo"
CPU_INTERRUPTS_URL = "interrupts"
CPU_ALL_URL = "all"
CPU_PERINFO_URL = "perinfo"
CPU_SENSOR_URL = "sensor"
CPU_PERSENSOR_URL = "persensor"
DISK_IO_URL = "io"
DISK_BLOCK_URL = "block"

URL_PARAM_CPUNUM = "cpuNum"
URL_PARAM_CPUNUM_DEFAULT = "all"
URL_PARAM_PHYID = "phyId"
URL_PARAM_COREID = "coreId"

EXCEPT_URL_ERROR = "Error url, please check ! "
EXCEPT_URL_PARAM_ERROR = "error cpu number,cpuNum like 0,1,2,3"
EXCEPT_RESULT_NONE = "get info is None, please check."
EXCEPT_DEFAULT = "some except happend."

LOG_START_SYSFILE = "monitor sysFile service log start: "
LOG_END_SYSFILE = "monitor sysFile service log end."
LOG_START_DISK = "monitor disk service log start: "
LOG_END_DISK = "monitor disk service log end."
LOG_START_CPU = "cpu monitor service log start: "
LOG_END_CPU = "cpu monitor service log end. "

DICT_KEYS_CPUCORE = "cpucore"
DICT_KEYS_CPU_NUMBER = "cpu_number"
DICT_KEYS_TIME = "time"
DICT_KEYS_DEV = "DEV"
DICT_KEYS_DEVNAME = "devname"
DICT_KEYS_NAME = "name"
DICT_KEYS_DEVICE = "Device:"
DICT_KEYS_RRQM = "rrqm/s"
DICT_KEYS_WRQM = "wrqm/s"
DICT_KEYS_MAJOR = "major"
DICT_KEYS_MINOR = "minor"
DICT_KEYS_DEV_STR = "dev"
JOINER = "-"
JOINER_SPECIAL = "&@"
SPACE_BLANK = " "
SPACE_NONE = ""
RE_SEPARATOR = "  +"
